name: Sync Commit Log and Create New Branch

on:
  push:
    branches:
      - main  # หรือชื่อ branch ที่คุณใช้

jobs:
  sync_and_create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync Commit Log
      run: |
        git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main
        COMMIT_LOG=$(git log --pretty=oneline HEAD..origin/main)
        echo "$COMMIT_LOG"

    - name: Create New Branch
      run: |
        CURRENT_TIME=$(date +'%H%M%S')
        NEW_BRANCH_NAME="log-$CURRENT_TIME"
        git checkout -b $NEW_BRANCH_NAME
        git push origin $NEW_BRANCH_NAME
