name: CI Auto Branching on Data Change

on:
  push:
    branches:
      - main

jobs:
  check_data_changes:
    runs-on: ubuntu-latest

    outputs:
      data_changed: ${{ steps.check.outputs.data_changed }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'

    - name: Check for data changes
      id: check
      run: |
        if [ $(git rev-parse --is-inside-work-tree) ]; then
          if git diff --name-only HEAD~1 HEAD -- | grep 'src/'; then
            echo "data_changed=true" >> $GITHUB_ENV
          else
            echo "data_changed=false" >> $GITHUB_ENV
          fi
        else
          echo "data_changed=false" >> $GITHUB_ENV
        fi

  create_branch:
    needs: check_data_changes
    runs-on: ubuntu-latest
    if: ${{ data_changed == 'true' }} # ลบ env ออกจากนี้

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'

    - name: Configure Git
      run: |
        git config user.name "dornrock123"
        git config user.email "krisd3214@gmail.com"

    - name: Create new branch
      run: |
        BRANCH_NAME=update-data-$(date +%Y%m%d%H%M%S)
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m "Automated update data branch creation"
        git push origin $BRANCH_NAME

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: $BRANCH_NAME
        title: "Automated Update Data Branch"
        body: "This pull request contains automated updates to data files."
