name: Sync Commit Log

on:
  push:
    branches:
      - main  # หรือชื่อ branch ที่คุณใช้

jobs:
  sync_commit_log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync Commit Log
      run: |
        git fetch --depth=1 origin +refs/heads/main:refs/remotes/origin/main
        git log --pretty=oneline HEAD..origin/main
