name: CI Auto Branching on Data Change

on:
  push:
    branches:
      - main

jobs:
  check_data_changes:
    runs-on: ubuntu-latest

    outputs:
      data_changed: ${{ steps.check.outputs.data_changed }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v3 # Updated to use Node.js 20

    - name: Check for data changes
      id: check
      run: |
        if [ $(git rev-parse --is-inside-work-tree) ]; then
          if git diff --name-only HEAD~1 HEAD -- | grep 'src/'; then
            echo "::set-output name=data_changed::true"
          else
            echo "::set-output name=data_changed::false"
          fi
        else
          echo "::set-output name=data_changed::false"
        fi

  create_branch:
    needs: check_data_changes
    runs-on: ubuntu-latest
    if: needs.check_data_changes.outputs.data_changed == 'true'

    steps:
    - name: Check out repository
      uses: actions/checkout@v3 # Updated to use Node.js 20

    - name: Configure Git
      run: |
        git config user.name "dornrock123"
        git config user.email "krisd3214@gmail.com"

    - name: Create new branch
      run: |
        BRANCH_NAME=update-data-$(date +%Y%m%d%H%M%S)
        git checkout -b $BRANCH_NAME
        git add .
        git commit -m "Automated update data branch creation"
        git push origin $BRANCH_NAME

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5 # Ensure this action is compatible with Node.js 20
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: $BRANCH_NAME
        title: "Automated Update Data Branch"
        body: "This pull request contains automated updates to data files."
